<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        {
            $users = [
                [
                    'id_role' => 1,
                    'id_jabatan_fungsional' => null,
                    'id_universitas' => null,                    
                    'id_pangkat_dosen' => null,
                    'gelar_depan' => null,
                    'gelar_belakang' => null,
                    'name' => 'SuperAdmin',
                    'no_rek' => null,
                    'npwp' => null,
                    'nidn' => null,
                    'file_serdos' => null,
                    'tanggal_lahir' => '1985-01-01',
                    'tempat_lahir' => 'Surabaya',
                    'status' => 'aktif',
                    'image' => null,
                    'email' => 'superadmin@gmail.com',
                    'email_verified_at' => now(),
                    'password' => Hash::make('super123'),
                    'remember_token' => null,
                ],
                [
                    'id_role' => 2,
                    'id_jabatan_fungsional' => null,
                    'id_universitas' => null,                    
                    'id_pangkat_dosen' => null,
                    'gelar_depan' => null,
                    'gelar_belakang' => null,
                    'name' => 'Verifikator',
                    'no_rek' => null,
                    'npwp' => null,
                    'nidn' => null,
                    'file_serdos' => null,
                    'tanggal_lahir' => '1985-01-01',
                    'tempat_lahir' => 'Surabaya',
                    'status' => 'aktif',
                    'image' => null,
                    'email' => 'verifikator@gmail.com',
                    'email_verified_at' => now(),
                    'password' => Hash::make('password'),
                    'remember_token' => null,
                ],
                [
                    'id_role' => 3,
                    'id_jabatan_fungsional' => null,
                    'id_universitas' => null,                    
                    'id_pangkat_dosen' => null,
                    'gelar_depan' => null,
                    'gelar_belakang' => null,
                    'name' => 'Perencanaan',
                    'no_rek' => null,
                    'npwp' => null,
                    'nidn' => null,
                    'file_serdos' => null,
                    'tanggal_lahir' => '1985-01-01',
                    'tempat_lahir' => 'Surabaya',
                    'status' => 'aktif',
                    'image' => null,
                    'email' => 'perencanaan@gmail.com',
                    'email_verified_at' => now(),
                    'password' => Hash::make('password'),
                    'remember_token' => null,
                ],
                [
                    'id_role' => 4,
                    'id_jabatan_fungsional' => null,
                    'id_universitas' => null,                    
                    'id_pangkat_dosen' => null,
                    'gelar_depan' => null,
                    'gelar_belakang' => null,
                    'name' => 'Keuangan',
                    'no_rek' => null,
                    'npwp' => null,
                    'nidn' => null,
                    'file_serdos' => null,
                    'tanggal_lahir' => '1985-01-01',
                    'tempat_lahir' => 'Surabaya',
                    'status' => 'aktif',
                    'image' => null,
                    'email' => 'keuangan@gmail.com',
                    'email_verified_at' => now(),
                    'password' => Hash::make('password'),
                    'remember_token' => null,
                ],

                [
                    'id_role' => 5,
                    'id_jabatan_fungsional' => null,
                    'id_universitas' => 1,                    
                    'id_pangkat_dosen' => null,
                    'gelar_depan' => 'Dr.',
                    'gelar_belakang' => 'PhD',
                    'id_bank' => 1,
                    'name' => 'John Doe',
                    'masa_kerja' => '5 Tahun 10 Bulan',
                    'awal_belajar' => '2021-02-02',
                    'akhir_belajar' => '2023-02-02',
                    'nama_rekening' => 'John D',
                    'no_rek' => '1234567890',
                    'npwp' => '0987654321',
                    'nidn' => '0123456789',
                    'file_serdos' => null,
                    'tanggal_lahir' => '1985-01-01',
                    'tempat_lahir' => 'Jakarta',
                    'tipe_dosen' => null,
                    'status' => 'belajar',
                    'image' => null,
                    'email' => 'john.doe@example.com',
                    'email_verified_at' => now(),
                    'password' => Hash::make('password'),
                    'remember_token' => null,
                ],
                [
                    'id_role' => 5,
                    'id_jabatan_fungsional' => null,
                    'id_universitas' => 1,                    
                    'id_pangkat_dosen' => null,
                    'gelar_depan' => null,
                    'gelar_belakang' => null,
                    'id_bank' => 1,
                    'name' => 'Jane Smith',
                    'nama_rekening' => 'J Smith',
                    'no_rek' => '9876543210',
                    'npwp' => '1234509876',
                    'nidn' => '0987612345',
                    'file_serdos' => null,
                    'tanggal_lahir' => '1990-02-02',
                    'tempat_lahir' => 'Bandung',
                    'status' => 'aktif',
                    'image' => '/images/cak_imin.jpeg',
                    'email' => 'jane.smith@example.com',
                    'email_verified_at' => now(),
                    'password' => Hash::make('password'),
                    'remember_token' => null,
                ],
                [
                    'id_role' => 5,
                    'id_jabatan_fungsional' => null,
                    'id_universitas' => 1,                    
                    'id_pangkat_dosen' => null,
                    'gelar_depan' => null,
                    'gelar_belakang' => null,
                    'name' => 'Alice Johnson',
                    'no_rek' => '5432109876',
                    'npwp' => '8765432109',
                    'nidn' => '6543210987',
                    'file_serdos' => null,
                    'tanggal_lahir' => '1988-03-03',
                    'tempat_lahir' => 'Surabaya',
                    'status' => 'aktif',
                    'image' => null,
                    'email' => 'alice.johnson@example.com',
                    'email_verified_at' => now(),
                    'password' => Hash::make('password'),
                    'remember_token' => null,
                ],
                [
                    'id_role' => 5,
                    'id_jabatan_fungsional' => null,
                    'id_universitas' => 1,                    
                    'id_pangkat_dosen' => null,
                    'gelar_depan' => null,
                    'gelar_belakang' => null,
                    'name' => 'Michael Brown',
                    'no_rek' => '1122334455',
                    'npwp' => '3344556677',
                    'nidn' => '1122443355',
                    'file_serdos' => null,
                    'tanggal_lahir' => '1992-04-04',
                    'tempat_lahir' => 'Medan',
                    'status' => 'aktif',
                    'image' => null,
                    'email' => 'michael.brown@example.com',
                    'email_verified_at' => now(),
                    'password' => Hash::make('password'),
                    'remember_token' => null,
                ],
                [
                    'id_role' => 5,
                    'id_jabatan_fungsional' => null,
                    'id_universitas' => 1,                    
                    'id_pangkat_dosen' => null,
                    'gelar_depan' => null,
                    'gelar_belakang' => null,
                    'name' => 'David Williams',
                    'no_rek' => '6677889900',
                    'npwp' => '9988776655',
                    'nidn' => '3344556677',
                    'file_serdos' => null,
                    'tanggal_lahir' => '1987-05-05',
                    'tempat_lahir' => 'Yogyakarta',
                    'status' => 'aktif',
                    'image' => null,
                    'email' => 'david.williams@example.com',
                    'email_verified_at' => now(),
                    'password' => Hash::make('password'),
                    'remember_token' => null,
                ],
                [
                    'id_role' => 6,
                    'id_jabatan_fungsional' => null,
                    'id_universitas' => null,                    
                    'id_pangkat_dosen' => null,
                    'gelar_depan' => null,
                    'gelar_belakang' => null,
                    'name' => 'Auditor',
                    'no_rek' => null,
                    'npwp' => null,
                    'nidn' => null,
                    'file_serdos' => null,
                    'tanggal_lahir' => '1985-01-01',
                    'tempat_lahir' => 'Surabaya',
                    'status' => 'aktif',
                    'image' => null,
                    'email' => 'auditor@gmail.com',
                    'email_verified_at' => now(),
                    'password' => Hash::make('password'),
                    'remember_token' => null,
                ],

                [
                    'id_role' => 7,
                    'id_jabatan_fungsional' => null,
                    'id_universitas' => 1,                    
                    'id_pangkat_dosen' => null,
                    'gelar_depan' => null,
                    'gelar_belakang' => null,
                    'name' => 'OP PT 17 Banyuwangi',
                    'no_rek' => '6677889900',
                    'npwp' => '9988776655',
                    'nidn' => '3344556677',
                    'file_serdos' => null,
                    'tanggal_lahir' => '1987-05-05',
                    'tempat_lahir' => 'Yogyakarta',
                    'status' => 'aktif',
                    'image' => null,
                    'email' => 'oppt@gmail.com',
                    'email_verified_at' => now(),
                    'password' => Hash::make('password'),
                    'remember_token' => null,
                ],

            ];

            $firstNames = ['John', 'Jane', 'Michael', 'Sarah', 'David', 'Emily', 'Robert', 'Jessica', 'Daniel', 'Linda'];
            $lastNames = ['Doe', 'Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Garcia', 'Martinez', 'Rodriguez', 'Taylor'];

            // Add 30 more dosen with role ID 5
            for ($i = 1; $i <= 30; $i++) {
                $firstName = $firstNames[array_rand($firstNames)];
                $lastName = $lastNames[array_rand($lastNames)];
                $fullName = $firstName . ' ' . $lastName;

                $users[] = [
                        'id_role' => 5,
                        'id_jabatan_fungsional' => null,
                        'id_universitas' => rand(1, 15), // Random university ID from 1 to 15
                        'id_pangkat_dosen' => null,
                        'gelar_depan' => 'Dr.', // You can randomize this if needed
                        'gelar_belakang' => 'PhD', // You can randomize this if needed
                        'id_bank' => 1,
                        'name' => $fullName,
                        'masa_kerja' => rand(1, 10) . ' Tahun ' . rand(1, 12) . ' Bulan',
                        'awal_belajar' => Carbon::create(rand(2018, 2021), rand(1, 12), rand(1, 28))->toDateString(),
                        'akhir_belajar' => Carbon::create(rand(2022, 2025), rand(1, 12), rand(1, 28))->toDateString(),
                        'nama_rekening' => $fullName,
                        'no_rek' => '123456789' . rand(0, 9),
                        'npwp' => '098765432' . rand(0, 9),
                        'nidn' => '012345678' . rand(0, 9),
                        'file_serdos' => null,
                        'tanggal_lahir' => Carbon::create(rand(1970, 1990), rand(1, 12), rand(1, 28))->toDateString(),
                        'tempat_lahir' => 'Jakarta',
                        'tipe_dosen' => null,
                        'status' => 'belajar', // Fixed status
                        'image' => null,
                        'email' => strtolower($firstName . '.' . $lastName . $i . '@example.com'),
                        'email_verified_at' => now(),
                        'password' => Hash::make('password'),
                        'remember_token' => null,
                    ];
            }

            foreach ($users as $user) {
                User::create($user);
            }
        }
    }
}